sudo: false
language: rust
rust:
- nightly
- beta
- stable
matrix:
  allow_failures:
  - rust: nightly
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH
script:
- |
  travis-cargo build &&
  travis-cargo test &&
  travis-cargo bench &&
  travis-cargo --only stable doc
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
after_success:
- travis-cargo --only stable doc-upload
- travis-cargo coveralls --no-sudo
notifications:
  email:
    on_success: never
env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=dev
  - secure: 
  - secure: sI5ofmuH9BLrRbUEOvkezGSZnGpaDG5d3BCiBOAIGkZ1Y+UT7iztXIyx17sb1WyLFortuNcQgguC7ys+eB6O644M47PLsH7fzZXYiIJeTv19X9WzSyGLtP9YPyXam+K3+h6UBKhQSCtxKWf3ZW1JybcS76fEf5clN6/Az3JsKREkQ/B2hH6o4AYV81R+7vlo4xmg4ONtpB6vwgZkY7fFcOQdPRLUN/WvTNzV8n3huBZvaqm2v9+K6HGyR8JVm7jnVp3/fIThlprNS7OY8A6X009Sn4uQ+joB/wYrdkbi3Uz8fkxyZqLZkWAbK/8MmR33foFSMpVNwEVOKOMsl5VcBy4/XziA6qKRIkR26xI3jHB7uWK9PMZ3ttYPBLSa8QUY3Go8hROzjVTe4dz0pDllaEvejEWVoQXp3hizNuKEjnQ3eDQpC+f82rO3Sd2TiEurkruinSm6HmoqFhQ3jPYl71YG4+50d6RAoSJNOowYKVR7wGZovadYICG1ZxJaXJUpE5ZD2i9I2Anct7mr2ce3LGtKv+lhiNGntIF/0v05P0O2vRh1VwdEzOl8YrJL5+4hO0DQFxXl87iCcYh5MoMqf+lF9sgNRxiAfbMCMy2p3MULkwIZoCfyeTatSUF+XbsKVxd/qTRdUCgn8GI6pm9YoMZw2cogk+S2ISa4h/Sky1Y=
